[project]
name = "funai"
version = "1.0.11"
description = "funai"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [ "funsecret>=1.4.84", "farlog>=1.1.7", "openai>=1.0.0",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [ "pytest>=7.0.0",]
