[project]
name = "funai"
version = "1.0.10"
description = "funai"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "funsecret>=1.4.84", "funutil>=1.0.62", "openai>=1.0.0",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [ "pytest>=7.0.0",]
